server:
  port: 9091
  max-http-request-header-size: 1MB

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-appdb
    username: postgres
    password: Saifuddin@#1998
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

keycloak:
  server-url: http://localhost:9090
  realm: erp
  admin:
    client-id: admin-cli
    username: admin
    password: Saifuddin@#2026

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: erp-web-client
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:9091/swagger-ui/oauth2-redirect.html

    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true

logging:
  level:
    org.springframework.security: INFO